### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by sydneybmunizaga**
Changed version of Node

### CODE REVIEW

**Comment by contrast-jeremiahp** [comment]
@miketmoore @jday3 any thoughts on what to test and how we can test this?

**Comment by fushi** [comment]
The best way to test this change would be to see if the pipelines that use the resultant image still work as expected. I've done some of this already.

**Review by jday3 — APPROVED** [review]
I'm not sure this image is used any longer

**Comment by contrast-jeremiahp** [comment]
Is this PR still valid? Can this be closed or merged?

**Comment by jday3** [comment]
> Is this PR still valid? Can this be closed or merged?

I'm not sure that it's needed, but I'll go ahead and merge it in case.

**Pull request merged**
